### ISSUE TITLE
Dimmer integration

### ISSUE THREAD

**Issue by Sanderbloem050** [bokub/rgb-light-card#10]
Is there an possibility to add a dimmer to the card so you can set color and brightness apart?

**Comment by bokub** [comment]
Yes, you can have some icons that only change the color, and some others that only change the brightness.

Example:

```yml
type: custom:rgb-light-card
entity: light.example_light
colors:
# The 2 following will change the color
- hs_color:
  - 0
  - 100
- hs_color:
  - 180
  - 100
# The 2 following will change the brightness
- brightness: 255
- brightness: 100

```
