### ISSUE TITLE
Custom element doesn't exist: rgb-light-card -- after installing via HACS

### ISSUE THREAD

**Issue by wsw70** [bokub/rgb-light-card#17]
I tried to install RGB Light Card via HACS, this went fine:

![image](https://user-images.githubusercontent.com/1345886/75115636-a8610080-5660-11ea-8389-e4dbabc136bb.png)

I then tried to add verbatim the example from the documentation to my `ui-lovelace.yaml` file (I added the previous two entries to match with the screenshot below):

```
- entities:
(...)
    - light.salon_bambou
    - light.salon_tete
    - type: 'custom:rgb-light-card'
      entity: light.salon_bambou
      colors:
          # Any option of the light.turn_on service can be used in each color
          - rgb_color:
                - 255
                - 127
                - 255
            brightness: 220
            transition: 1
          - hs_color:
                - 60
                - 30
            icon_color: '#fff8b0' # Override icon color
 ```

Unfortunately the component is not known:

![image](https://user-images.githubusercontent.com/1345886/75115624-8f584f80-5660-11ea-8c45-0380f06c2964.png)

It looks like, however, that it is installed at the right place:

```
/etc/docker/container-data/hass(master*) # ls                                                                                                                            root@srv
automations.yaml  configuration.yaml  deps              harmony_salon.conf  home-assistant_v2.db  ui-lovelace.yaml
configuration     custom_components   emulated_roku.py  home-assistant.log  known_devices.yaml    www

/etc/docker/container-data/hass(master*) # ls www/community/rgb-light-card/card.js                                                                                       root@srv
www/community/rgb-light-card/card.js
 ```

**Not being knowledgeable with HACS (and so-so with HA), is there some other step to take in order to fix this?** (I already restarted HA in case just adding a component via HACS would not be enough)
