### ISSUE TITLE
Feature Request: add white

### ISSUE THREAD

**Issue by hell1337hound** [bokub/rgb-light-card#25]
Hey i was wondering if you could add white support? as i have a RGBW device that id love to set colours for

Thanks!

**Comment by bokub** [comment]
Hello,

If your light is supported by Home Assistant, then it's automatically supported by this card.

Try to do what you want using the [`light.turn_on`](https://www.home-assistant.io/integrations/light#service-lightturn_on) service, then you just have to copy the parameters into this card.

Maybe `white_value` or `color_temp` are the options you need

**Comment by XRyu** [comment]
Not a duplicate :)
Its totally supported and works - its just some asthetics - when you just use the code as i posted above, there are just grey cells.
There could be an other default cell color, i think this might already help and when only brightness is specified the color might be faded through the alphachannel in rgba CSS :)
I have done this, and like it now: 

```
type: entities
entities:
  - type: custom:rgb-light-card
    entity: light.light_gruppe_wohnzimmer
    justify: around
    colors:
      - brightness_pct: 0
        label: Aus
      - brightness_pct: 10
        label: 10%
        icon_color: rgba(255, 215, 0, 0.1)
      - brightness_pct: 30
        label: 30%
        icon_color: rgba(255, 215, 0, 0.3)
      - brightness_pct: 50
        label: 50%
        icon_color: rgba(255, 215, 0, 0.5)
      - brightness_pct: 70
        label: 70%
        icon_color: rgba(255, 215, 0, 0.7)
      - brightness_pct: 100
        icon_color: rgba(255, 215, 0, 1)
        label: 100%
show_state: true
icon_height: 50px
```
Looks like this:
![image](https://user-images.githubusercontent.com/131995/136525743-00280db6-0539-42a0-a344-880ace0e8665.png)


Vs formerly this:
![image](https://user-images.githubusercontent.com/131995/136525867-58e3498b-4c92-475a-9ea3-28b7a8a7635a.png)
