### ISSUE TITLE
Theme variables for shadow and spread

### ISSUE THREAD

**Issue by agneevX** [bokub/rgb-light-card#31]
There's shadow visible in light themes, but with dark themes these shadows are not legible.

Please expose variables to set the color of this shadow and the spread upon hover.

You can use `ha-card-box-shadow` if that's helpful.

**Comment by bokub** [comment]
Sorry but this is really too specific. I don't want this card to have a thousand configuration options, because:
- It would be a mess to maintain
- The documentation would be impossible to read

However, you can:
- [download this card](https://github.com/bokub/rgb-light-card/releases/download/1.7.1/card.js)
- Edit the code
- Use your edited card it in your own Home Assistant setup

**Comment by agneevX** [comment]
It's not about options, it's about the fact that the shadows are only visible in light themes, not dark themes.

**Comment by bokub** [comment]
> Please expose variables

You mean CSS variables?

**Comment by agneevX** [comment]
Yep, that's what I meant by "theme variables" :)

**Comment by agneevX** [comment]
This is what I'm referring to FYI. 

<img src="https://user-images.githubusercontent.com/19761269/98459358-2a2d9580-21c0-11eb-974e-4b1e9870326e.png" width="350">


<img src="https://user-images.githubusercontent.com/19761269/98459366-30bc0d00-21c0-11eb-9afa-a7543a23b0db.png" width="350">


<img src="https://user-images.githubusercontent.com/19761269/98459372-34e82a80-21c0-11eb-97f8-fb978a891687.png" width="350">

**Comment by raffertyp1** [comment]
I came here looking for a way to hide the box shadows. I haven't been able to successfully hide them with card-mod. While I'd be glad to see a configuration option or even theme variables, can you offer any guidance on how to hide them through CSS styling?

**Comment by spencerthayer** [comment]
@agneevX how do you have a gradient?

**Comment by agneevX** [comment]
Good question. Please check my setup repo.

**Comment by steviehs** [comment]
Hmm... how do I get this nice slider right from Desk Light?

**Comment by agneevX** [comment]
> Hmm... how do I get this nice slider right from Desk Light?

> Please check my setup repo.

**Comment by bokub** [comment]
@steviehs You can use the [slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row) card like this:

```yaml
type: entities
show_header_toggle: false
entities:
  - entity: light.example
    toggle: true
    type: 'custom:slider-entity-row' # <====== Add this line
  - type: 'custom:rgb-light-card'
    entity: light.example
    colors:
      - ...
```

**Comment by steviehs** [comment]
Thanks, I guess I have to learn a lot to get this all look and work nicely :-)

**Comment by bokub** [comment]
Hello @agneevX ,
I might have some free time to work on this, but first I have a question:

How do you plan to "customize" these CSS variables ?

**Comment by agneevX** [comment]
I'd say setting the ability to set the box-shadow would be how I'd want to customize it.

**Comment by bokub** [comment]
OK, but let's say I use a CSS variable containing the box-shadow, **how** would you change it?

Could you provide an example maybe?

**Comment by agneevX** [comment]
Just `box-shadow` perhaps?

```yml
type: entities
entities:
  - type: 'custom:rgb-light-card'
    entity: light.example_light
    box-shadow: "0px 0px 5px 0px rgba(0,0,0,0.62)"
    colors:
      - rgb_color:
        - 255
        - 127
        - 255
        brightness: 220
        transition: 1
```

**Comment by bokub** [comment]
OK, so what you have in mind is a new option, not just a CSS variable that you can edit...

I told you I didn't want "have a thousand configuration options", and you told me "it's not about options", and asked me to "expose variables" instead, so I'm a little bit confused.

**Comment by bokub** [comment]
So no, I won't add a new option just for this, **but** there is another alternative that you should consider:

- Install [Lovelace Card Mode](https://github.com/thomasloven/lovelace-card-mod)
- Add a `card_mod` key in the bottom of the card configuration
- Customize the card exactly like you want using CSS!

For example, here is what I can do with the following YAML code:

![image](https://user-images.githubusercontent.com/17952318/155496602-c827c083-fdae-4866-88d2-3e8f6aee4e26.png)


```yaml
type: entities
show_header_toggle: false
entities:
  - entity: light.example
  - type: 'custom:rgb-light-card'
    entity: light.example
    colors:
      - rgb_color:
          - 234
          - 136
          - 140
      - rgb_color:
          - 251
          - 180
          - 139
      - rgb_color:
          - 136
          - 198
          - 237
      - rgb_color:
          - 140
          - 231
          - 185
    card_mod:
      style: |
        .color-circle {
          box-shadow: 4px 4px 4px 0px rgba(255,255,0,0.6);
        }
```

I hope it solves your problem!
