### ISSUE TITLE
[Feature Request] Can you add the ability to adjust brightness please?

### ISSUE THREAD

**Issue by cnmarch6** [bokub/rgb-light-card#35]
[Feature Request] Can you add the ability to adjust brightness please?

**Comment by peetereczek** [comment]
Just merge with another custom:slider-entity-row card and you will get expected result

![image](https://user-images.githubusercontent.com/42431204/103012822-6e8caf00-453c-11eb-9de8-ee198b575715.png)

> entities:
>  - type: 'custom:slider-entity-row'
>    toggle: true
>    hide_when_off: true
>    entity: light.sonoff_1000ee2034
>  - type: 'custom:rgb-light-card'
>    entity: light.sonoff_1000ee2034
>    hide_when_off: true

**Comment by bokub** [comment]
Thanks @peetereczek !

If you need another example, here is my configuration:

```yaml
type: entities
entities:
- type: 'custom:slider-entity-row'
  entity: light.example
  name: LED
  toggle: true
- type: 'custom:rgb-light-card'
  colors:
  - # some color
  entity: light.example
```

![image](https://user-images.githubusercontent.com/17952318/103040103-c3e3b300-4572-11eb-877c-1aef88b36b9d.png)
