### ISSUE TITLE
Icon auto-coloring doesn't work when using xy_color mode

### ISSUE THREAD

**Issue by BrainDamage** [bokub/rgb-light-card#37]
Icon auto-coloring doesn't work when using xy_color mode, it always displays a grey icon no matter the colour or the brightness

```
type: entities
entities:
    - type: 'custom:rgb-light-card'
      entity: light.example_light
      colors:
          # this works
          - rgb_color:
                - 255
                - 127
                - 255
          # this too
          - hs_color:
                - 60
                - 30
          # this results in a gray icon, instead of white
          - xy_color:
              - 0.33
              - 0.33
            brightness: 255
          # this too results in a gray icon, instead of purple
          - xy_color:
              - 0.217
              - 0.077
```
