### ISSUE TITLE
Color Temperature/CCT support?

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [bokub/rgb-light-card#39]
I've got a bunch of adjustable color temperature bulbs and would love to be able to adjust their values with a card like this.

**Comment by Jan-Ka** [comment]
Hi, not the maintainer but just stumbled over your comment. You can adjust your bulbs color temperature with something like this:

```yaml
entity: light.my_light
type: 'custom:rgb-light-card'
colors:
  - kelvin: 3500
    transition: 1
  - kelvin: 5000
    transition: 1
  - kelvin: 2700
    transition: 1
```

Tested this with Athom (Tasmota) Bulbs but as long as you can change the color temp in hassio, you should be able to do it with this card.
