### ISSUE TITLE
RGBW (and RGBWW?) support

### ISSUE THREAD

**Issue by PaoloTK** [bokub/rgb-light-card#44]
Home Assistant 2021.5 changed the way lights work so that RGBW and RGBWW lights can use 4 and 5 entries lists to control each channel. After updating I've noticed that the card doesn't work anymore with the white_value attribute, which is to be expected since it's been deprecated. However trying to use "rgbw_color" doesn't work either. I've verified it to work on the light by issuing a command from the developers tool menu. Here's an example from one of my cards:

```
type: entities
entities:
  - entity: light.bedroom
    name: Bedroom Light
  - type: 'custom:rgb-light-card'
    entity: light.bedroom
    justify: around
    colors:
      - rgbw_color:
          - 0
          - 0
          - 0
          - 255
        brightness: 255
        transition: 1
      - rgb_color:
          - 0
          - 0
          - 0
        white_value: 255
        brightness: 255
        transition: 1
```
I would expect the RGBW light to turn on the white channel at max brightness but neither option works.
