### ISSUE TITLE
Can't send data with call-service?

### ISSUE THREAD

**Issue by dennisbrouwer91** [bokub/rgb-light-card#49]
Hi,

I'm trying to link the different colors that I have to scripts, and send the color to the script as a variable.
But when I try this I get the message that the "data" part is not allowed. I tried putting it everywhere, but I can't get the var to go to the service.

```
type: entities
show_header_toggle: false
entities:
  - type: custom:rgb-light-card
    entity: light.eetkamer
    colors:
      - type: call-service
        service: script.turn_on
        service_data:
          entity_id: script.woonkamer_color
          color: blue
        icon_color: '#90b2ec'
      - type: call-service
        service: script.turn_on
        service_data:
          entity_id: script.woonkamer_color
          mycolor: pink
        icon_color: '#FF3374'
      - type: call-service
        service: script.turn_on
        service_data:
          entity_id: script.woonkamer_color
          data:
            color: green
        icon_color: '#8AFF33'
title: Eetkamer lampen
state_color: true
```

Anyone with advice?

**Comment by LordGaav** [comment]
This worked in my case for a select item exposed by WLED. The trick is not using a nested `data` key:

```
  - type: call-service
    service: select.select_option
    service_data:
      entity_id: select.wled_preset
      option: Solid
    label: Solid
```
