### ISSUE TITLE
Potability to set scene rather than colour?

### ISSUE THREAD

**Issue by gdeboos** [bokub/rgb-light-card#5]
It would be awesome if we could run a scene as well as set colour for single light.
Especially because you can use gradients as the background colour of the icon.

**Comment by bokub** [comment]
That's an excellent idea.

How would you imagine the configuration to be like ?

**Comment by gdeboos** [comment]
Without deep diving into this, I assume you are currently forwarding the color configuration data to the light.turn_on service.

Could you look for a new config option of _type_ and where it is set to scene, run the scene from another new option? Default _type_ to something like _light_ for backwards compatibility.

Something like:

```
colors:
  - type: light
    rgb_color:
    - 255
    - 127
    - 255
  - type: scene
    scene: my_scene_name
  - hs_color:
    # no type but defaults to light
    - 60
    - 30
```

**Comment by bokub** [comment]
Fixed in 1.3.0 !

The config is like this: 

```yaml
colors:
  - type: scene
    entity_id: scene.my_scene
  - hs_color:
    - 60
    - 30
```
