### ISSUE TITLE
color_temp problem

### ISSUE THREAD

**Issue by vsimanin** [bokub/rgb-light-card#51]
Can't get the color_temp command to work through the card. This example throws an error:

```
- rgb_color:
     - 255
     - 255
     - 255
  color_temp: 255
  brightness: 255
```

Can you add an example with changing this parameter? Thanks!
