### ISSUE TITLE
How to change size of card?

### ISSUE THREAD

**Issue by PrzemekSkw** [bokub/rgb-light-card#54]
Hello, I try to add rgb-light-card to my horizontal stack with some custom button cards. It looks like this:
![Zrzut ekranu z 2021-12-03 11-12-18](https://user-images.githubusercontent.com/25219988/144585626-889ef5e6-7bb0-47d9-b983-a3e26cc83224.png)

I try to add:
```
styles:
  card:
    - height: 90px
    - width: 340px
```
but nothing happen.
It's possible to fit that card here?
Regards.
