### ISSUE TITLE
Phillips Hue color_temp values

### ISSUE THREAD

**Issue by beachie13** [bokub/rgb-light-card#57]
color_temp is supported by my philips hue bulbs but if I use color_temp with a value of 355 I get a failed to call service error. Is there a particular way to address color temp value for Phillips hue. 

- color_temp:
          - 355
        brightness: 100
        transition: 1

**Comment by bokub** [comment]
Hi, `color_temp` isn't supposed to be an array.

Here is an example of a correct configuration:

```yaml
- color_temp: 355
  brightness: 100
  transition: 1
```
