### ISSUE TITLE
Insert 'spacer' between icons to group them

### ISSUE THREAD

**Issue by deepcoder** [bokub/rgb-light-card#58]
Thanks for your work on this project, very useful!

I would like to break the row of icons into two parts: day temperatures and night colors.

If I put the following in:
```
            colors:
                - color_temp: 153
                  brightness: 255
                - color_temp: 500
                  brightness: 255
                - icon_color : black
                - hs_color:
                  - 216
                  - 24
                  brightness: 13
```
the black icon still executes the on/off call for the light. I would like it to do nothing if possible. Or if you have another way you could recommend to 'group' the icons.

Thx!
