### ISSUE TITLE
Allow setting a mdi: icon for icon_color

### ISSUE THREAD

**Issue by michaelarnauts** [bokub/rgb-light-card#6]
Currently, it's possible to set a image for `icon_color` like `icon_color: center/120% url('https://www.home-assistant.io/images/favicon-192x192.png')`.

It would be great if we could just use the `mdi:` or `far:`-icons that are available in Home Assistant.

**Comment by bokub** [comment]
It's not a bad idea, but how would you imagine the look of it?

An icon in a circle or just an icon? What would be the color? And the background color?
This seems out of the scope of this card...

If you need deep customization, [the button-entity-row card](https://github.com/custom-cards/button-entity-row) is more suited for your needs

**Comment by michaelarnauts** [comment]
I was thinking it could just be the same as the image url, but maybe a better api would be to split the color and the image.

Like:
```yaml
type: entities
entities:
    - type: 'custom:rgb-light-card'
      colors:
          # First icon calls a script
          - type: script
            entity_id: script.night_mode
            icon_color: 'linear-gradient(#777777, #151515)'
            icon_image: 'mdi:hotel'
            #icon_image: 'https://www.home-assistant.io/images/favicon-192x192.png'
```

The icon_image should also have a `no-repeat` set. This is currently not the case in the example, causing a repetitive icon to be displayed when setting the size below 100%.
