### ISSUE TITLE
Bug on mobile when put in head of lovelace-fold-entity-row

### ISSUE THREAD

**Issue by watermarkhu** [bokub/rgb-light-card#60]
The described error below is observed on mobile in combination with [lovelace-fold-entity-row](https://github.com/thomasloven/lovelace-fold-entity-row). 

When the rgb-light-card is put in the `head:` of the lovelace-fold-entity-row, and every one of the color list items have the type `call-service` with no `entity:` specified for the rgb-light-card, **only on mobile** the rgb buttons are not clickable, but fold/unfolds the lovelace-fold-entity-row.  

```yaml
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      colors:
        - icon_color: ' linear-gradient(15deg, #984F01, #FF880D, #FFEB8A)'
          service: input_select.select_option
          service_data:
            entity_id: input_select.scene_kitchen
            option: all_lights_on
          type: call-service
        - icon_color: 'linear-gradient(15deg, #000000, #FF880D, #FFEB8A)'
          service: input_select.select_option
          service_data:
            entity_id: input_select.scene_kitchen
            option: cooking
          type: call-service
      justify: center
      size: 44
      type: custom:rgb-light-card
    entities:
      - light.kitchen_pendant
      - light.kitchen_countertop
title: Without entity specified
```
This can be circumvented by adding a dummy `entity:` for the rgb-light-card.. 

```yaml
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      entity: 
      colors:
        - icon_color: ' linear-gradient(15deg, #984F01, #FF880D, #FFEB8A)'
          service: input_select.select_option
          service_data:
            entity_id: input_select.scene_kitchen
            option: all_lights_on
          type: call-service
        - icon_color: 'linear-gradient(15deg, #000000, #FF880D, #FFEB8A)'
          service: input_select.select_option
          service_data:
            entity_id: input_select.scene_kitchen
            option: cooking
          type: call-service
      justify: center
      size: 44
      type: custom:rgb-light-card
    entities:
      - light.kitchen_pendant
      - light.kitchen_countertop
title: Without entity specified
```

https://gfycat.com/jubilantmagnificentboilweevil
