### ISSUE TITLE
Entity group must be a light

### ISSUE THREAD

**Issue by steviehs** [bokub/rgb-light-card#62]
I guess this is not a bug but a noobs question:

```
type: entities
show_header_toggle: true 
entities:
  - entity: group.bad_ug_decke
  - type: custom:rgb-light-card
    entity: group.bad_ug_decke
    colors:
      - rgb_color:
          - 234
          - 136
          - 140
        brightness: 255
        transition: 1
```

gives me: `Entity 'group.bad_ug_decke' must be a light`
The standard group card works fine on this group and allows me to set colours and temperature...
What am I doing wrong?
