### ISSUE TITLE
Should it work with eWeLight ZB-CL02?

### ISSUE THREAD

**Issue by and7ey** [bokub/rgb-light-card#66]
Here is Exposes tab from Zigbee2mqtt:
<img width="1136" alt="Снимок экрана 2022-09-11 в 22 54 29" src="https://user-images.githubusercontent.com/900474/189546547-c33760a4-001a-430e-9c9f-af5a2e1a6063.png">
but when I uses your example, it doesn't change the light color and brightness.

**Comment by bokub** [comment]
I have no idea what you're talking about. How am I supposed to help you if you don't even give an example of what you tried to do so far?

**Comment by and7ey** [comment]
I've taken your example:
```
type: entities
show_header_toggle: false
entities:
    # Card configuration starts here
    - type: 'custom:rgb-light-card'
      entity: light.0x123455 # here is my id
      colors:
          # Any option of the light.turn_on service can be used in each color
          - rgb_color:
                - 255
                - 127
                - 255
            brightness: 220
            transition: 1
          - hs_color:
                - 60
                - 30
            icon_color: '#fff8b0' # Override icon color
```
but it doesn't work with my light (the details of the light are given below) - when I press the color button, nothing happens.
