### ISSUE TITLE
Configuration for example cards in README

### ISSUE THREAD

**Issue by carlos-sarmiento** [bokub/rgb-light-card#7]
I'm trying to replicate the colors used on the first two examples in the README file. But haven't found it anywhere. Would you mind sharing them?

**Comment by xaviml** [comment]
These are the colors used in the "Justify" section:
```yaml
colors:
  - rgb_color:
      - 234
      - 136
      - 140
  - rgb_color:
      - 251
      - 180
      - 140
  - rgb_color:
      - 135
      - 198
      - 237
  - rgb_color:
      - 249
      - 222
      - 139
  - rgb_color:
      - 139
      - 231
      - 185
```

**Comment by rasssta** [comment]
Please add it to the README :)

**Comment by bokub** [comment]
Big card:
```yaml
colors:
- rgb_color:
    - 234
    - 136
    - 140
- rgb_color:
    - 251
    - 180
    - 140
- rgb_color:
    - 135
    - 198
    - 237
- rgb_color:
    - 249
    - 222
    - 139
- rgb_color:
    - 139
    - 231
    - 185
- icon_color: 'linear-gradient(15deg, #206383, #73c1be)'
- icon_color: 'linear-gradient(15deg, #ff9fa5, #fdcdeb)'
```

Small card: 
```yaml
colors:
- icon_color: 'linear-gradient(-30deg, #ffc9a9, #ffefcf)'
- icon_color: 'linear-gradient(-30deg, #00fff7, #fb00ff)'
- icon_color: 'linear-gradient(-30deg, #256ef9, #59ffce)'
```
