### ISSUE TITLE
Specify a color with brightness *and* color_temp?

### ISSUE THREAD

**Issue by iandoesallthethings** [bokub/rgb-light-card#70]
I saw in another closed issue that you can't use color_temp and rgb_color at the same time which totally makes sense. But is there a way to specify both brightness *and* temperature?

I'm looking for this kind of thing:

```yaml
- type: 'custom:rgb-light-card'
  entity: light.bedroom_group
      colors:
        - name: dark
          brightness: 50
          color_temp: 500
        
        - name: warm
          brightness: 255
          color_temp: 500
        
        - name: bright
          brightness: 255
          color_temp: 300
```

This might have more to do with the light.turn_on service, but I can't quite find a definitive answer in the docs whether this is possible.
