### ISSUE TITLE
Hide main entity of card

### ISSUE THREAD

**Issue by SAOPP** [bokub/rgb-light-card#72]
Hey! Cool realization of the idea. I looked at the card and immediately realized that this is what I'm looking for, but here's one problem / idea, is it possible to add the ability to hide the main entity of the card? For example, I would like to hide such a card under the condition that if the lighting is off, this card is not shown. Accordingly, I do not need a duplicate entity, it would be cool if this is implemented.

**Comment by bokub** [comment]
Hi @SAOPP

I'm not sure I understand what part you would like to hide (a screenshot might help).

Did you try to use a native [conditional card](https://www.home-assistant.io/dashboards/conditional/) ?

**Comment by SAOPP** [comment]
Here is on:

![image](https://user-images.githubusercontent.com/5647009/211773797-2578224e-72b4-44fb-bdc9-9a9534609532.png)

I want to show rgb colors only.

**Comment by SAOPP** [comment]
> Did you try to use a native [conditional card](https://www.home-assistant.io/dashboards/conditional/) ?

Yep, when my lights is on I shoe additional timer and etc data, and if we 'r talking 'bout rgb bulbs, so your card is cool for this, I will shoe you my example what 'bout I'm talking...

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/211775008-6d2c48cd-ef88-4e05-a8ee-2d034c38c69e.png)

I mean this, in your card is present entity id, will be better if we can make main entity hide. Display colors only.

**Comment by bokub** [comment]
The red part is **not** part of the card, this is just an example.

Please read the documentation again, it's explained:

```yaml
type: entities
show_header_toggle: false
entities:
    # Displays the light entity. It's optional
    - entity: light.example_light

    # Card configuration starts here
    - type: 'custom:rgb-light-card'
      entity: light.example_light
```
