### ISSUE TITLE
Possibility to change the shape

### ISSUE THREAD

**Issue by lukuhn** [bokub/rgb-light-card#78]
Hey it would be cool if it was possible to change the shape of the colors e.g. by using the border radius atrribut to turn the circle into a rectangle with rounded corners.

**Comment by bokub** [comment]
Hi,

You should be able to do that using the [card-mod](https://github.com/thomasloven/lovelace-card-mod) module

**Comment by bokub** [comment]
Using border radius, as you suggested earlier

```yml
- type: custom:rgb-light-card
  card_mod:
    style: '.color-circle { border-radius: 5px }'
```
