### ISSUE TITLE
Allow unit types for size other than px.

### ISSUE THREAD

**Issue by szerencl** [bokub/rgb-light-card#82]
Size currently only supports size in px unit. It would be nice to use other units as well.
e.g.:
```
type: entities
show_header_toggle: false
entities:
    - entity: light.example_light
    - type: 'custom:rgb-light-card'
      entity: light.example_light
      size: 2rem <--------------------------------- relative unit
      colors:
          - rgb_color:
                - 255
                - 127
                - 255
            brightness: 220
            transition: 1
          - hs_color:
                - 60
                - 30
            icon_color: '#fff8b0' # Override icon color
```
